# Generated by Django 3.2.5 on 2021-07-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stupid_count', models.IntegerField(default=0)),
                ('fat_count', models.IntegerField(default=0)),
                ('dumb_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.UserAuth')),
            ],
        ),
    ]
